import { LEARNING_PATH_PROGRESS_GUEST } from '../constants.js';

// The key for storing the paths themselves
const LEARNING_PATHS_KEY_GUEST = 'knowledgeTester_learningPaths_guest';

let learningPaths = {}; // Stores the structure of the paths { pathId: pathObject }
let progress = {}; // Stores the progress { pathId: { completedSteps: [] } }

function loadFromStorage() {
    try {
        const storedPaths = localStorage.getItem(LEARNING_PATHS_KEY_GUEST);
        learningPaths = storedPaths ? JSON.parse(storedPaths) : {};

        const storedProgress = localStorage.getItem(LEARNING_PATH_PROGRESS_GUEST);
        progress = storedProgress ? JSON.parse(storedProgress) : {};
    } catch (error) {
        console.warn("Could not access localStorage for learning paths.", error);
        learningPaths = {};
        progress = {};
    }
}

function savePaths() {
    try {
        localStorage.setItem(LEARNING_PATHS_KEY_GUEST, JSON.stringify(learningPaths));
    } catch (error) {
        console.warn("Could not save learning paths to localStorage.", error);
    }
}

function saveProgress() {
    try {
        localStorage.setItem(LEARNING_PATH_PROGRESS_GUEST, JSON.stringify(progress));
    } catch (error) {
        console.warn("Could not save learning path progress to localStorage.", error);
    }
}

// --- Public API ---

/**
 * Saves a newly generated learning path.
 * @param {object} pathData The path object generated by the AI.
 * @returns {object} The full path object with a unique ID and steps.
 */
export function saveNewPath(pathData) {
    const pathId = `path_${Date.now()}`;
    const newPath = {
        id: pathId,
        name: pathData.name,
        description: `An AI-generated path to help you learn about ${pathData.name}.`,
        steps: pathData.steps.map((step, index) => ({
            ...step,
            id: `${pathId}_step_${index + 1}`
        }))
    };
    learningPaths[pathId] = newPath;
    savePaths();
    return newPath;
}

export function getLearningPath(pathId) {
    return learningPaths[pathId] || null;
}

export function getAllLearningPaths() {
    // Returns an array of all saved path objects
    return Object.values(learningPaths);
}

export function getProgressForPath(pathId) {
    return progress[pathId] || { completedSteps: [] };
}

export function markStepComplete(pathId, stepId) {
    if (!progress[pathId]) {
        progress[pathId] = { completedSteps: [] };
    }
    if (!progress[pathId].completedSteps.includes(stepId)) {
        progress[pathId].completedSteps.push(stepId);
        saveProgress();
    }
}

// Initialize from storage on load
loadFromStorage();